---
## reference: https://github.com/geerlingguy/ansible-role-apache/blob/master/.travis.yml

services: docker

env:
  - distro: centos6
    playbook: test.yml -t install
  - distro: centos7
    playbook: test.yml -t install
  - distro: ubuntu1404
    playbook: test.yml -t install
  - distro: ubuntu1604
    playbook: test.yml -t install


script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

  # my test code
  - 'docker exec ${container_id} ls /usr/bin/mysql | grep "/usr/bin/mysql"'

# notifications:
  # webhooks: https://galaxy.ansible.com/api/v1/notifications/
