- name: start mysqld
  service:
    name: mysqld
    state: restarted

- name: Get host_name
  setup: filter=ansible_hostname
  register: get_ansible_facts

- shell: "cat /var/log/mysqld.log | grep 'temporary password' | grep -oP ': .+' | grep -oP ' .+' | xargs"
  register: temp_passwd
  no_log: True

- name: Update MySQL root password for localhost root account (5.7.x).
  shell: >
    mysql -u root --connect-expired-password --password="{{ temp_passwd.stdout }}" -NBe 'ALTER USER "root"@"localhost" IDENTIFIED WITH mysql_native_password BY "{{ mysql_password }}";'
  no_log: True

- name: remove the MySQL test database
  mysql_db: name=test state=absent login_user=root login_password={{ mysql_password }}
  no_log: True

- name: Copy {{ default_mysql_version }} my.cnf
  template:
    src: "my-{{ default_mysql_version }}.cnf"
    backup: yes
    dest: /etc/my.cnf
    group: root
    owner: root
    mode: 0644
  become: yes
  notify: restart mysqld
