- name: restart mysqld
  service:
    name: mysqld
    state: restarted

- name: restart mysql
  service:
    name: mysql
    state: restarted

- name: systemctl restart mysql
  systemd:
    name: mysql
    state: restarted
  when: ansible_virtualization_type != "docker"
